"""
Wiku bpy Script — Generated by Dalang-AI
Build: wiku_20261001_052604
Deskripsi: Meja kerja minimalis industrial 1200x600mm
Dibuat: 2026-10-01T05:26:04.152424

CARA PAKAI DI BLENDER:
  1. Buka Blender → Scripting tab
  2. Paste seluruh script ini ke editor
  3. Klik Run Script (atau Alt+P)
  4. Cek Output Console: AGENT_OK = berhasil, AGENT_FAIL = ada error

Non-Commercial — CC BY-NC 4.0 — Dalang-AI by Khoirul Anam
"""

import bpy
import bmesh
import math
import os

# ─── Reset Scene ─────────────────────────────────────────────────────────────
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for block in list(bpy.data.meshes):
    bpy.data.meshes.remove(block)

# ── Meja Kerja Minimalis ──────────────────────────────────────
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 0.001  # 1 BU = 1mm

def make_box(name, loc, dim):
    bpy.ops.mesh.primitive_cube_add(location=loc)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = (dim[0]/2, dim[1]/2, dim[2]/2)
    bpy.ops.object.transform_apply(scale=True)
    return obj

# Tabletop — 1200mm x 600mm x 25mm
tabletop = make_box('Tabletop', (0, 0, 0.7375), (1.200, 0.600, 0.025))

# 4 Kaki meja — 40mm x 40mm x 720mm
leg_positions = [
    ( 0.560,  0.260, 0.360),
    (-0.560,  0.260, 0.360),
    ( 0.560, -0.260, 0.360),
    (-0.560, -0.260, 0.360),
]
legs = []
for i, pos in enumerate(leg_positions):
    leg = make_box(f'Leg_{i+1}', pos, (0.040, 0.040, 0.720))
    legs.append(leg)

# Material kayu
mat = bpy.data.materials.new(name='Wood')
mat.use_nodes = True
bsdf = mat.node_tree.nodes.get('Principled BSDF')
bsdf.inputs['Base Color'].default_value = (0.45, 0.28, 0.15, 1)
bsdf.inputs['Roughness'].default_value = 0.7
tabletop.data.materials.append(mat)
for leg in legs:
    leg.data.materials.append(mat)

_objects_to_check = ["Tabletop", "Leg_1", "Leg_2", "Leg_3", "Leg_4"]

# ─── Geometry Gate ────────────────────────────────────────────────────────────
def geometry_gate(obj_name, min_verts=4):
    obj = bpy.data.objects.get(obj_name)
    if obj is None:
        print("AGENT_FAIL: Object '" + obj_name + "' tidak ditemukan setelah build.")
        return False
    if len(obj.data.vertices) < min_verts:
        print("AGENT_FAIL: Object '" + obj_name + "' hanya punya " + str(len(obj.data.vertices)) + " vertex (min: " + str(min_verts) + ").")
        return False
    return True

# ─── Export ───────────────────────────────────────────────────────────────────
try:
    _gate_pass = all([geometry_gate(n) for n in _objects_to_check])
    if not _gate_pass:
        raise RuntimeError("Geometry gate GAGAL — lihat pesan AGENT_FAIL di atas.")

    _out = os.path.join(os.path.expanduser("~"), "Desktop", "wiku_20261001_052604.glb")
    bpy.ops.export_scene.gltf(
        filepath=_out,
        export_format='GLB',
        export_apply=True,
        export_materials='EXPORT',
    )
    print(f"AGENT_OK — GLB disimpan ke: {_out}")
except Exception as _e:
    print(f"AGENT_FAIL: {_e}")
